<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="0" hostname="intel" name="pytest" skipped="0" tests="1" time="27.664" timestamp="2020-03-11T08:42:30.903661"><testcase classname="test_e2e.TestOne" file="test_e2e.py" line="14" name="test_e2e" time="27.548"><system-err>--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\python\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\python\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Python\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\python\lib\site-packages\_pytest\config\__init__.py&quot;, line 92, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\python\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\python\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\python\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\python\lib\site-packages\_pytest\main.py&quot;, line 197, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\python\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\python\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\python\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\python\lib\site-packages\_pytest\main.py&quot;, line 271, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\python\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\python\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 84, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 99, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 185, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 209, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 237, in from_call
    result = func()
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 210, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\python\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\python\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 134, in pytest_runtest_call
    item.runtest()
  File &quot;c:\python\lib\site-packages\_pytest\python.py&quot;, line 1445, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\python\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\python\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\python\lib\site-packages\_pytest\python.py&quot;, line 167, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\lenovo\Desktop\My Projects\Code\Python\Selenium_python_Udemy\PythonSelFramework1\tests\test_e2e.py&quot;, line 37, in test_e2e
    log.info(&quot;Text received from application is &quot;, success_text)
Message: &apos;Text received from application is &apos;
Arguments: (&apos;Ã—\nSuccess! Thank you! Your order will be delivered in next few weeks :-).&apos;,)
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\python\lib\site-packages\_pytest\logging.py&quot;, line 70, in format
    return super().format(record)
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\python\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\python\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Python\Scripts\py.test.exe\__main__.py&quot;, line 7, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\python\lib\site-packages\_pytest\config\__init__.py&quot;, line 92, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\python\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\python\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\python\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\python\lib\site-packages\_pytest\main.py&quot;, line 197, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\python\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\python\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\python\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\python\lib\site-packages\_pytest\main.py&quot;, line 271, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\python\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\python\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 84, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 99, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 185, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 209, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 237, in from_call
    result = func()
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 210, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\python\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\python\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\python\lib\site-packages\_pytest\runner.py&quot;, line 134, in pytest_runtest_call
    item.runtest()
  File &quot;c:\python\lib\site-packages\_pytest\python.py&quot;, line 1445, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\python\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\python\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\python\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\python\lib\site-packages\_pytest\python.py&quot;, line 167, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\lenovo\Desktop\My Projects\Code\Python\Selenium_python_Udemy\PythonSelFramework1\tests\test_e2e.py&quot;, line 37, in test_e2e
    log.info(&quot;Text received from application is &quot;, success_text)
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 1577, in _log
    self.handle(record)
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 1587, in handle
    self.callHandlers(record)
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 1649, in callHandlers
    hdlr.handle(record)
  File &quot;c:\python\lib\logging\__init__.py&quot;, line 950, in handle
    self.emit(record)
  File &quot;c:\python\lib\site-packages\_pytest\logging.py&quot;, line 301, in emit
    logging.StreamHandler.emit(self, record)
Message: &apos;Text received from application is &apos;
Arguments: (&apos;Ã—\nSuccess! Thank you! Your order will be delivered in next few weeks :-).&apos;,)
</system-err></testcase></testsuite></testsuites>